/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarnRouteImport } from './routes/warn'
import { Route as PurchaseRouteImport } from './routes/purchase'
import { Route as KeySuccessRouteImport } from './routes/key-success'
import { Route as InfoRouteImport } from './routes/info'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GetKeyRouteImport } from './routes/get-key'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as BannedRouteImport } from './routes/banned'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const WarnRoute = WarnRouteImport.update({
  id: '/warn',
  path: '/warn',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRoute = PurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const KeySuccessRoute = KeySuccessRouteImport.update({
  id: '/key-success',
  path: '/key-success',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GetKeyRoute = GetKeyRouteImport.update({
  id: '/get-key',
  path: '/get-key',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const BannedRoute = BannedRouteImport.update({
  id: '/banned',
  path: '/banned',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_authenticated/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/banned': typeof BannedRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/get-key': typeof GetKeyRoute
  '/help': typeof HelpRoute
  '/info': typeof InfoRoute
  '/key-success': typeof KeySuccessRoute
  '/purchase': typeof PurchaseRoute
  '/warn': typeof WarnRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/banned': typeof BannedRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/get-key': typeof GetKeyRoute
  '/help': typeof HelpRoute
  '/info': typeof InfoRoute
  '/key-success': typeof KeySuccessRoute
  '/purchase': typeof PurchaseRoute
  '/warn': typeof WarnRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/banned': typeof BannedRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/get-key': typeof GetKeyRoute
  '/help': typeof HelpRoute
  '/info': typeof InfoRoute
  '/key-success': typeof KeySuccessRoute
  '/purchase': typeof PurchaseRoute
  '/warn': typeof WarnRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/banned'
    | '/credits'
    | '/dashboard'
    | '/faq'
    | '/get-key'
    | '/help'
    | '/info'
    | '/key-success'
    | '/purchase'
    | '/warn'
    | '/admin'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/banned'
    | '/credits'
    | '/dashboard'
    | '/faq'
    | '/get-key'
    | '/help'
    | '/info'
    | '/key-success'
    | '/purchase'
    | '/warn'
    | '/admin'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/banned'
    | '/credits'
    | '/dashboard'
    | '/faq'
    | '/get-key'
    | '/help'
    | '/info'
    | '/key-success'
    | '/purchase'
    | '/warn'
    | '/_authenticated/admin'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BannedRoute: typeof BannedRoute
  CreditsRoute: typeof CreditsRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  GetKeyRoute: typeof GetKeyRoute
  HelpRoute: typeof HelpRoute
  InfoRoute: typeof InfoRoute
  KeySuccessRoute: typeof KeySuccessRoute
  PurchaseRoute: typeof PurchaseRoute
  WarnRoute: typeof WarnRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warn': {
      id: '/warn'
      path: '/warn'
      fullPath: '/warn'
      preLoaderRoute: typeof WarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase': {
      id: '/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof PurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/key-success': {
      id: '/key-success'
      path: '/key-success'
      fullPath: '/key-success'
      preLoaderRoute: typeof KeySuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-key': {
      id: '/get-key'
      path: '/get-key'
      fullPath: '/get-key'
      preLoaderRoute: typeof GetKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banned': {
      id: '/banned'
      path: '/banned'
      fullPath: '/banned'
      preLoaderRoute: typeof BannedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BannedRoute: BannedRoute,
  CreditsRoute: CreditsRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  GetKeyRoute: GetKeyRoute,
  HelpRoute: HelpRoute,
  InfoRoute: InfoRoute,
  KeySuccessRoute: KeySuccessRoute,
  PurchaseRoute: PurchaseRoute,
  WarnRoute: WarnRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
